export const GETPOKIMON = 'GETPOKIMON';
export const CLEARPOKIMON = 'CLEARPOKIMON';
export const GETPOKIMOVE1 = 'GETPOKIMOVE1';
export const GETPOKIMOVE2 = 'GETPOKIMOVE2';
export const GETPOKIMOVE3 = 'GETPOKIMOVE3';
export const GETPOKIMOVE4 = 'GETPOKIMOVE4';


